spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://127.0.0.1:3306/partyzone?serverTimezone=CET
    username: root
    password: test
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
