spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring?serverTimezone=CET
    username: root
    password: test
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      dll-auto: validate
    properties:
      hibernate:
        format_sql: true
